---
title: "Example where self-learning fails"
author: "Jesse H. Krijthe"
output: pdf_document
---
```{r setup, echo=FALSE, warning=FALSE, results="hide"}
library(RSSL)
library(dplyr,warn.conflicts = FALSE)
library(ggplot2)
library(ggthemes)
library(magrittr)
library(knitr)
library(scales)
library(extrafont,quietly = TRUE)
opts_chunk$set(echo=FALSE, warning=FALSE, dev="pdf")
```

```{r}
library(ggthemes)
library(scales)
theme_classy <-  function(base_size=12) { 
  theme_foundation(base_size=base_size) +
  theme(rect=element_rect(fill=NA,colour=NA),
        legend.position="bottom",
        text=element_text(family="Palatino",size = base_size,colour="black"),
        line=element_line(size=0,colour="black"),
        axis.title.y=element_text(angle=0),
        axis.line=element_line(size=0.5,colour = "black",linetype=1),
        axis.ticks=element_line(size=0.5,color="black"),
        panel.grid=element_line(size=0.1,colour="grey",linetype = 2),
        panel.grid.minor=element_line(size=0.0,colour=NA,linetype = 2),
        strip.text=element_text(size=base_size*1.5),
        legend.text=element_text(size=base_size))
}
```

```{r problem}
datasets <- list("2 Gaussian Expected"=generate2ClassGaussian(n=2000,d=2,expected=TRUE),
                 "2 Gaussian Non-Expected"=generate2ClassGaussian(n=2000,d=2,expected=FALSE))
formulae <- list("2 Gaussian Expected"=formula(Class~.),
                 "2 Gaussian Non-Expected"=formula(Class~.))

classifiers <- list("Supervised" = 
                      function(X,y,X_u,y_u) { LeastSquaresClassifier(X,y)},
                    "Self-learning" = 
                      function(X,y,X_u,y_u) { SelfLearning(X,y,X_u,method = LeastSquaresClassifier)})

measures <- list("Error" =  measure_error,
                 "Loss" = measure_losstest,
                 "Loss labeled" = measure_losslab,
                 "Loss Lab+Unlab" = measure_losstrain
)
```

```{r fig.width=12, fig.height=5}
datasets_plot <- datasets 
datasets_plot[[1]] <- datasets[[1]] %>% mutate(Dataset=names(datasets)[[1]])
datasets_plot[[2]] <- datasets[[2]] %>% mutate(Dataset=names(datasets)[[2]])
bind_rows(datasets_plot) %>% 
  ggplot(aes(x=X1,y=X2,color=Class)) +
  geom_point(alpha=0.6) +
  facet_wrap(~Dataset) +
  theme_classy(8) +
  coord_equal() +
  scale_color_manual(values=c("orange","purple"))
```

We take 10 labeled objects and an increasing number of unlabeled objects and repeat this 100 times.

```{r run-learningcurves, results='hide', cache=TRUE}
res_lc <- LearningCurveSSL(formulae,datasets,classifiers=classifiers,measures=measures,verbose=TRUE,repeats=100,n_l=10,sizes = 2^(1:10))
```

```{r fig.width=12, fig.height=5}
res_lc$results %>% 
  dplyr::filter(Measure=="Error") %>% 
  dplyr::filter(Classifier %in% c("Supervised","Self-learning")) %>%
  mutate(Measure=NULL) %>% 
  group_by(`Number of unlabeled objects`,Classifier, Dataset) %>% 
  summarize(Mean=mean(value),SE=sd(value)/sqrt(n())) %>% 
  ungroup %>% 
  ggplot(aes(x=`Number of unlabeled objects`,y=Mean)) + 
  scale_x_continuous(trans = log2_trans(),expand=c(0.1,0),breaks=c(2,4,8,16,32,64,128,256,512,1024)) +
  facet_wrap(~Dataset) +
  geom_line(aes(linetype=Classifier)) +
  geom_pointrange(aes(ymin=Mean-1*SE,ymax=Mean+1*SE)) +
  scale_y_continuous(limits=c(0.0,0.35),expand=c(0,0)) + 
  theme_classy() +
  ylab("Error")
```
